<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from ur5_joint_limited_robot.urdf.xacro | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="ur5" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- ur5 arm -->
 <!-- common stuff -->
  <gazebo>
    <plugin filename="libgazebo_ros_control.so" name="ros_control">
      <!--robotNamespace>/UR5/</robotNamespace-->
      <!--robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType-->
    </plugin>
    <!--
    <plugin name="gazebo_ros_power_monitor_controller" filename="libgazebo_ros_power_monitor.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>1.0</updateRate>
      <timeout>5</timeout>
      <powerStateTopic>power_state</powerStateTopic>
      <powerStateRate>10.0</powerStateRate>
      <fullChargeCapacity>87.78</fullChargeCapacity>     
      <dischargeRate>-474</dischargeRate>
      <chargeRate>525</chargeRate>
      <dischargeVoltage>15.52</dischargeVoltage>
      <chargeVoltage>16.41</chargeVoltage>
    </plugin>
-->
  </gazebo>


<property name="pi" value="3.1415926535898" />

  <!-- Inertia parameters -->
  <property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
  <property name="shoulder_mass" value="3.7000" />
  <property name="upper_arm_mass" value="8.3930" />
  <property name="forearm_mass" value="2.2750" />
  <property name="wrist_1_mass" value="1.2190" />
  <property name="wrist_2_mass" value="1.2190" />
  <property name="wrist_3_mass" value="0.1879" />

  <property name="shoulder_cog" value="0.0 0.00193 -0.02561" />
  <property name="upper_arm_cog" value="0.0 -0.024201 0.2125" />
  <property name="forearm_cog" value="0.0 0.0265 0.11993" />
  <property name="wrist_1_cog" value="0.0 0.110949 0.01634" />
  <property name="wrist_2_cog" value="0.0 0.0018 0.11099" />
  <property name="wrist_3_cog" value="0.0 0.001159 0.0" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <!--
    DH for UR5:
    a = [0.00000, -0.42500, -0.39225,  0.00000,  0.00000,  0.0000]
    d = [0.089159,  0.00000,  0.00000,  0.10915,  0.09465,  0.0823]
    alpha = [ 1.570796327, 0, 0, 1.570796327, -1.570796327, 0 ]
    q_home_offset = [0, -1.570796327, 0, -1.570796327, 0, 0]
    joint_direction = [-1, -1, 1, 1, 1, 1]
    mass = [3.7000, 8.3930, 2.2750, 1.2190, 1.2190, 0.1879]
    center_of_mass = [ [0, -0.02561, 0.00193], [0.2125, 0, 0.11336], [0.11993, 0.0, 0.0265], [0, -0.0018, 0.01634], [0, 0.0018,0.01634], [0, 0, -0.001159] ]
  -->

  <property name="q_home_offset_1" value="0.0" />
  <property name="ur5_d1" value="0.089159" />
  <property name="ur5_a1" value="0.0" />
  <property name="alpha_1" value="${pi/2}" />
  

  <property name="q_home_offset_2" value="-${pi/2}" />
  <property name="ur5_d2" value="0.0" />
  <property name="ur5_a2" value="-0.42500" />
  <property name="alpha_2" value="0.0" />
  
  <property name="q_home_offset_3" value="0.0" />
  <property name="ur5_d3" value="0.0" />
  <property name="ur5_a3" value="-0.39225" />
  <property name="alpha_3" value="0.0" />
  
  <property name="q_home_offset_4" value="-${pi/2}" />
  <property name="ur5_d4" value="0.10915" />
  <property name="ur5_a4" value="0.0" />
  <property name="alpha_4" value="${pi/2}" />

  <property name="q_home_offset_5" value="0.0" />
  <property name="ur5_d5" value="0.09465" />
  <property name="ur5_a5" value="0.0" />
  <property name="alpha_5" value="-${pi/2}" />

  <property name="q_home_offset_6" value="0.0" />
  <property name="ur5_d6" value="0.0823" />
  <property name="ur5_a6" value="0.0" />
  <property name="alpha_6" value="0.0" />

<!--Joint 0(theta, d, a, alpha)-0.00371039 0.0958959 -0.00194819 1.57275
Joint 1(theta, d, a, alpha)-0.0309971 -0.000454111 0.421472 0.000740345
Joint 2(theta, d, a, alpha)0.00469988 -0.000462854 0.390623 -0.0110371
Joint 3(theta, d, a, alpha)0.00031729 -0.109632 0.00326656 1.56457
Joint 4(theta, d, a, alpha)0.0012977 0.0935537 -0.00195301 -1.5639
Joint 5(theta, d, a, alpha)3.14159 -0.0800224 0.00554286 3.14034-->


  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <property name="shoulder_offset" value="0.13585" />  <!-- measured from model -->
  <property name="elbow_offset" value="-0.1197" /> <!-- measured from model -->

  <!-- link lengths used in model -->
  <property name="shoulder_height" value="${ur5_d1}" />
  <property name="upper_arm_length" value="${-ur5_a2}" />
  <property name="forearm_length" value="${-ur5_a3}" />
  <property name="wrist_1_length" value="${ur5_d4 - elbow_offset - shoulder_offset}" />
  <property name="wrist_2_length" value="${ur5_d5}" />
  <property name="wrist_3_length" value="${ur5_d6}" />
  <!--property name="shoulder_height" value="0.089159" /-->
  <!--property name="shoulder_offset" value="0.13585" /-->  <!-- shoulder_offset - elbow_offset + wrist_1_length = 0.10915 -->
  <!--property name="upper_arm_length" value="0.42500" /-->
  <!--property name="elbow_offset" value="0.1197" /-->       <!-- CAD measured -->
  <!--property name="forearm_length" value="0.39225" /-->
  <!--property name="wrist_1_length" value="0.093" /-->     <!-- CAD measured -->
  <!--property name="wrist_2_length" value="0.09465" /-->   <!-- In CAD this distance is 0.930, but in the spec it is 0.09465 -->
  <!--property name="wrist_3_length" value="0.0823" /-->

  <property name="shoulder_radius" value="0.060" />   <!-- manually measured -->
  <property name="upper_arm_radius" value="0.054" />  <!-- manually measured -->
  <property name="elbow_radius" value="0.060" />      <!-- manually measured -->
  <property name="forearm_radius" value="0.040" />    <!-- manually measured -->
  <property name="wrist_radius" value="0.045" />      <!-- manually measured -->

  <link name="base_link">
    <visual>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/visual/base.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/collision/base.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="4.0"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <inertia ixx="0.00443333156" ixy="0.0" ixz="0.0" iyy="0.00443333156" iyz="0.0" izz="0.0072"/>
    </inertial>
  </link>
  <joint name="shoulder_pan_joint" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_link"/>

    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 ${shoulder_height}"/><!--origin rpy="0.0 0.0 0.7853981625" xyz="0.0 0.0 0.089159"/-->

    <axis xyz="0 0 1"/>
    <limit effort="150.0" lower="-3.14159265" upper="3.14159265" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="shoulder_link">
    <visual>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/visual/shoulder.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/collision/shoulder.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="3.7"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <inertia ixx="0.010267495893" ixy="0.0" ixz="0.0" iyy="0.010267495893" iyz="0.0" izz="0.00666"/>
    </inertial>
  </link>
  <joint name="shoulder_lift_joint" type="revolute">
    <parent link="shoulder_link"/>
    <child link="upper_arm_link"/>
    <origin rpy="0.0 1.570796326795 0.0" xyz="0.0 0.13585 0.0"/>
    <axis xyz="0 1 0"/>
    <limit effort="150.0" lower="-3.14159265" upper="-0.1" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="upper_arm_link">
    <visual>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/visual/upper_arm.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/collision/upper_arm.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="8.393"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.28"/>
      <inertia ixx="0.22689067591" ixy="0.0" ixz="0.0" iyy="0.22689067591" iyz="0.0" izz="0.0151074"/>
    </inertial>
  </link>
  <joint name="elbow_joint" type="revolute">
    <parent link="upper_arm_link"/>
    <child link="forearm_link"/>
    <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
<!--origin rpy="0.0 0.0 0.0" xyz="0.0 -0.1197 0.425"/-->
    <axis xyz="0 1 0"/>
    <limit effort="150.0" lower="-3" upper="3" velocity="3.15"/> <!-- +/- 175 deg -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="forearm_link">
    <visual>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/visual/forearm.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/collision/forearm.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.275"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.25"/>
      <inertia ixx="0.049443313556" ixy="0.0" ixz="0.0" iyy="0.049443313556" iyz="0.0" izz="0.004095"/>
    </inertial>
  </link>
  <joint name="wrist_1_joint" type="revolute">
    <parent link="forearm_link"/>
    <child link="wrist_1_link"/>
    <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
    <!--origin rpy="0.0 1.570796326795 0.0" xyz="0.0 0.0 0.39225"/-->
    <axis xyz="0 1 0"/>
    <limit effort="28.0" lower="-3.92" upper="0.78" velocity="3.2"/><!-- -225 deg to 45 deg -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="wrist_1_link">
    <visual>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/visual/wrist_1.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/collision/wrist_1.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.219"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <inertia ixx="0.111172755531" ixy="0.0" ixz="0.0" iyy="0.111172755531" iyz="0.0" izz="0.21942"/>
    </inertial>
  </link>
  <joint name="wrist_2_joint" type="revolute">
    <parent link="wrist_1_link"/>
    <child link="wrist_2_link"/>
    <!--origin rpy="0.0 0.0 0.0" xyz="0.0 0.093 0.0"/-->
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
    <axis xyz="0 0 1"/>
    <limit effort="28.0" lower="-${pi}" upper="${pi}" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="wrist_2_link">
    <visual>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/visual/wrist_2.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/collision/wrist_2.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.219"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <inertia ixx="0.111172755531" ixy="0.0" ixz="0.0" iyy="0.111172755531" iyz="0.0" izz="0.21942"/>
    </inertial>
  </link>
  <joint name="wrist_3_joint" type="revolute">
    <parent link="wrist_2_link"/>
    <child link="wrist_3_link"/>
    <!--origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.09465"/-->
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
    <axis xyz="0 1 0"/>
    <limit effort="28.0" lower="-${pi}" upper="${pi}" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="wrist_3_link">
    <visual>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/visual/wrist_3.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/ur5/collision/wrist_3.stl"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1879"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <inertia ixx="0.0171364731454" ixy="0.0" ixz="0.0" iyy="0.0171364731454" iyz="0.0" izz="0.033822"/>
    </inertial>
  </link>
  <joint name="ee_fixed_joint" type="fixed">
    <parent link="wrist_3_link"/>
    <child link="ee_link"/>
    <!--origin rpy="-1.570796326795 0.0 0" xyz="0.0 0.0823 0.0"/-->
    <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="-1.570796326795 0.0 0" />
  </joint>
  <link name="ee_link">
    <collision>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.01 0 0"/>
    </collision>
  </link>
<!--TRANSMISSION FOR THE ARM-->
  <transmission name="shoulder_pan_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_pan_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="shoulder_pan_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="shoulder_lift_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_lift_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="shoulder_lift_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="elbow_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="elbow_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="wrist_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_1_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_1_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="wrist_2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_2_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_2_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="wrist_3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_3_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_3_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <link name="base"/>
  <joint name="base_link-base_fixed_joint" type="fixed">
    <!-- NOTE: this rotation is only needed as long as base_link itself is
                 not corrected wrt the real robot (ie: rotated over 180
                 degrees)
      -->
    <origin rpy="0 0 -3.14159265" xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="base"/>
  </joint>
  <link name="tool0"/>
  <joint name="wrist_3_link-tool0_fixed_joint" type="fixed">
    <origin rpy="-1.570796326795 0 0" xyz="0 0.0823 0"/>
    <parent link="wrist_3_link"/>
    <child link="tool0"/>
  </joint>
  <link name="world"/>
  <joint name="world_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
  </joint>

  <!-- ========================================== -->

  <!-- force torque sensor (robotiq) -->

  <link name="fts_robotside">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.65"/>
      <inertia ixx="0.000661171875" ixy="0" ixz="0" iyy="0.000661171875" iyz="0" izz="0.00117"/>
    </inertial>
    <visual>
      <origin rpy="0 ${pi} -1.570796326795" xyz="0 0 0.0375"/>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/robotiq-ft300/visual/ft300.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 ${pi} -1.570796326795" xyz="0 0 0.0375"/>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/robotiq-ft300/collision/ft300.stl"/>
      </geometry>
    </collision>
  </link>
  
  <!-- virtual measurement frame -->
  <joint name="measurment_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.01625"/>
    <parent link="fts_robotside"/>
    <child link="robotiq_force_torque_frame_id"/>
  </joint>
  <link name="robotiq_force_torque_frame_id"/>
  
  <!-- toolside frame -->
  <joint name="toolside_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.0375"/>
    <parent link="fts_robotside"/>
    <child link="fts_toolside"/>
  </joint>
  <link name="fts_toolside"/>

 <!-- ========================================== -->
 
  <link name="camera_robotside">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/egomo-1/visual/egomo-1.dae"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://egomo_ur5/meshes/egomo-1/collision/egomo-1.stl"/>
      </geometry>
    </collision>
  </link>

  <!-- Mount the force torque sensor (fts) to the robot -->

  <joint name="fts_to_robot" type="fixed" >
    <parent link="tool0" />
    <child link="fts_robotside" />
    <origin xyz="0 0 0.011" rpy="0 0 0" />
  </joint>

  <!-- Mount the cameras to the robot -->

  <joint name="camera_to_robot" type="fixed" >
    <parent link="tool0" />
    <child link="camera_robotside" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint> 


  <!-- ========================================== -->
  
<link name="robotiq_85_coupling">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_coupling.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0 0 0"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_coupling.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0 0 0"/>
  </collision>
</link>

<joint name="robotiq_85_base_joint" type="fixed">
  <parent link="robotiq_85_coupling"/>
  <child link="robotiq_85_base"/>
  <origin xyz="0 0 0.0109" rpy="0 0 0" />
</joint>

<link name="robotiq_85_base">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_base.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0 0 0"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_base.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0 0 0"/>
  </collision>
</link>

<link name="robotiq_85_finger_right_1">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_finger_right_1.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0.0305864 0 -0.0549191"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_finger_right_1.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0.0305864 0 -0.0549191"/>
  </collision>
</link>

<link name="robotiq_85_finger_right_2">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_finger_right_2.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0.0621231 0 -0.0511592"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_finger_right_2.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0.0621231 0 -0.0511592"/>
  </collision>
</link>

<link name="robotiq_85_finger_right_3">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_finger_right_3.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0.0127161 0 -0.0613987"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_finger_right_3.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0.0127161 0 -0.0613987"/>
  </collision>
</link>

<link name="robotiq_85_finger_right_4">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_finger_right_4.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0.0498492 0 -0.1048415"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_finger_right_4.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="0.0498492 0 -0.1048415"/>
  </collision>
</link>

<link name="robotiq_85_finger_left_1">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_finger_left_1.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="-0.0305864 0 -0.0549191"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_finger_left_1.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="-0.0305864 0 -0.0549191"/>
  </collision>
</link>

<link name="robotiq_85_finger_left_2">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_finger_left_2.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="-0.0621231 0 -0.0511592"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_finger_left_2.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="-0.0621231 0 -0.0511592"/>
  </collision>
</link>

<link name="robotiq_85_finger_left_3">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_finger_left_3.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="-0.0127161 0 -0.0613987"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_finger_left_3.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="-0.0127161 0 -0.0613987"/>
  </collision>
</link>

<link name="robotiq_85_finger_left_4">
  <visual>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/visual/gripper_finger_left_4.dae"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="-0.0498492 0 -0.1048415"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://egomo_ur5/meshes/robotiq-2-finger-85/collision/gripper_finger_left_4.stl"/>
    </geometry>
    <origin rpy="0 0 ${pi}" xyz="-0.0498492 0 -0.1048415"/>
  </collision>
</link>

<joint name="robotiq_85_finger_right_1_joint" type="continuous">
  <parent link="robotiq_85_base"/>
  <child link="robotiq_85_finger_right_1"/>
  <axis xyz="0 1 0"/>
  <origin rpy="0 0 0" xyz="-0.0305864 0 0.0549191"/>
  <limit effort="1000" lower="0" upper="0.811" velocity="2.0"/>
</joint>

<joint name="robotiq_85_finger_right_2_joint" type="fixed">
  <parent link="robotiq_85_finger_right_1"/>
  <child link="robotiq_85_finger_right_2"/>
  <axis xyz="0 1 0"/>
  <origin rpy="0 0 0" xyz="-0.0315367 0 -0.0037599"/>
</joint>

<joint name="robotiq_85_finger_right_3_joint" type="continuous">
  <parent link="robotiq_85_base"/>
  <child link="robotiq_85_finger_right_3"/>
  <axis xyz="0 1 0"/>
  <origin rpy="0 0 0" xyz="-0.0127161 0 0.0613987"/>
  <limit effort="1000" lower="0" upper="0.811" velocity="2.0"/>
  <mimic joint="robotiq_85_finger_right_1_joint" multiplier="1" offset="0"/>
</joint>

<joint name="robotiq_85_finger_right_4_joint" type="continuous">
  <parent link="robotiq_85_finger_right_3"/>
  <child link="robotiq_85_finger_right_4"/>
  <axis xyz="0 1 0"/>
  <origin rpy="0 0 0" xyz="-0.0371331 0 0.0434428"/>
  <mimic joint="robotiq_85_finger_right_1_joint" multiplier="-1" offset="0"/>
  <limit effort="1000" lower="-0.811" upper="0" velocity="2.0"/>
</joint>

<joint name="robotiq_85_finger_left_1_joint" type="continuous">
  <parent link="robotiq_85_base"/>
  <child link="robotiq_85_finger_left_1"/>
  <axis xyz="0 1 0"/>
  <origin rpy="0 0 0" xyz="0.0305864 0 0.0549191"/>
  <mimic joint="robotiq_85_finger_right_1_joint" multiplier="-1" offset="0"/>
  <limit effort="1000" lower="-0.811" upper="0" velocity="2.0"/>
</joint>

<joint name="robotiq_85_finger_left_2_joint" type="fixed">
  <parent link="robotiq_85_finger_left_1"/>
  <child link="robotiq_85_finger_left_2"/>
  <axis xyz="0 1 0"/>
  <origin rpy="0 0 0" xyz="0.0315367 0 -0.0037599"/>
</joint>

<joint name="robotiq_85_finger_left_3_joint" type="continuous">
  <parent link="robotiq_85_base"/>
  <child link="robotiq_85_finger_left_3"/>
  <axis xyz="0 1 0"/>
  <origin rpy="0 0 0" xyz="0.0127161 0 0.0613987"/>
  <mimic joint="robotiq_85_finger_right_1_joint" multiplier="-1" offset="0"/>
  <limit effort="1000" lower="-0.811" upper="0" velocity="2.0"/>
</joint>

<joint name="robotiq_85_finger_left_4_joint" type="continuous">
  <parent link="robotiq_85_finger_left_3"/>
  <child link="robotiq_85_finger_left_4"/>
  <axis xyz="0 1 0"/>
  <origin rpy="0 0 0" xyz="0.0371331 0 0.0434428"/>
  <mimic joint="robotiq_85_finger_right_1_joint" multiplier="1" offset="0"/>
  <limit effort="1000" lower="0" upper="0.811" velocity="2.0"/>
</joint>

  <!--transmission name="robotiq_85_finger_right_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="robotiq_85_finger_right_1_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="robotiq_85_finger_right_1_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission-->

<!-- ========================================== -->

 <!-- Mount the gripper to the force torque sensor -->
 <joint name="gripper_to_fts" type="fixed" >
    <parent link="fts_toolside" />
    <child link="robotiq_85_coupling" />
    <origin xyz="0 0 -0.003" rpy="0 0 0" />
  </joint> 

</robot>
